apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-crd 
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/rajkumar25maurya/argo-dep.git
    targetRevision: main
    path: nginx-crd

  destination:
    server: https://192.168.1.140:6443 
    namespace: nginx-crd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true